sylius_grid:
    grids:
        sherlockode_wishlist_admin:
            driver:
                name: doctrine/orm
                options:
                    class: "%sherlockode_wishlist.model.wishlist.class%"
                    repository:
                        method: createListQueryBuilder
            fields:
                id:
                    type: string
                    label: sherlockode_wishlist.wishlist.label.id
                    sortable: ~
                title:
                    type: twig
                    label: sherlockode_wishlist.wishlist.label.title
                    sortable: title
                    path: .
                    options:
                        template: "sherlockodeSyliusWishlistBundle:Backend:grid/_title.html.twig"
                public:
                    type: twig
                    label: sherlockode_wishlist.wishlist.label.public
                    sortable: ~
                    options:
                        template: SyliusUiBundle:Grid/Field:yesNo.html.twig
                user:
                    type: twig
                    label: sherlockode_wishlist.wishlist.label.user
                    sortable: user
                    path: .
                    options:
                        template: "sherlockodeSyliusWishlistBundle:Backend:grid/_user.html.twig"
                createdAt:
                    type: datetime
                    label: sherlockode_wishlist.wishlist.label.created_at
                    sortable: ~
                    options:
                        format: 'd-m-Y H:i'
                updatedAt:
                    type: datetime
                    label: sherlockode_wishlist.wishlist.label.updated_at
                    sortable: ~
                    options:
                        format: 'd-m-Y H:i'
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                title:
                    type: string
                    label: sherlockode_wishlist.wishlist.label.title
                    options:
                        fields: [title]
            sorting:
                createdAt: desc
